### ISSUE TITLE
Overloading 1.0

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Cpp-hacktoberfest23#10]
Create a 'Rectangle' class with two data members, length and breadth, and a function to calculate the area that is 'length*breadth'. The class has three constructors, which are as follows:

- a - no parameter - length and breadth values are both set to zero.

- b - using two numbers as parameters, one for length and one for breadth.
- c - Using a single number as a parameter - that number is assigned to both length and breadth.

Now, create objects of the 'Rectangle' class having none, one, and two parameters and print their areas.

**Comment by Pakeetharan** [comment]
Hi @chetannihith I'd like to do this, could you please assign this to me?
