### ISSUE TITLE
Overloading 2.0

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Cpp-hacktoberfest23#11]
Write a program to calculate the salary of Indian Railway employees. Three
are three types of employees in Indian railways. They are regular, daily wages
and consolidated employees. Gross Pay for the employees is calculated as
follows:

- a - regular employees = basic + HRA + (10%of DA * basic)
- b - Daily wages = wages per hour * number of hours
- c - Consolidated = a fixed amount

**Comment by Shubh2003** [comment]
@chetannihith i have added code for overloading can you please assign this issue to me
