### ISSUE TITLE
Employee - class and objects

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Cpp-hacktoberfest23#8]
Write a program by creating an 'Employee' class having the following functions and print
the final salary.

- 'getlnfo()' which takes the salary, number of hours of work per day of employee as parameters

- 'AddSal()' which adds $10 to the salary of the employee if it is less than $500.

- 'AddWork()' which adds $5 to the salary of the employee if the number of hours of work per day is more than 6 hours.

**Comment by Sarveshk76** [comment]
I would like to work on this issue
