### ISSUE TITLE
Multiple Inheritance

### ISSUE THREAD

**Issue by chetannihith** [chetannihith/Cpp-hacktoberfest23#9]
We want to calculate the total marks of each student of a class in Physics, Chemistry, and Mathematics and the average marks of the class. The number of students in the class is entered by the user. Create a class named Marks with data members for roll number, name, and marks. Create three other classes inheriting the Marks class, namely Physics, Chemistry, and Mathematics, which are used to define marks in the individual subjects of each student. The roll number of each student will be generated automatically.

**Comment by Pakeetharan** [comment]
Hi @chetannihith I'd like to do this, could you please assign this to me?
